name: Build Toto

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app

#      - name: Trigger Render Deployment
#        run: |
#          curl -X POST https://api.render.com/deploy/srv-cum85apu0jms73blduv0?key=Z2iSfUyE534